{{- if .Values.variables.configmap -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "search-services.fullname" . }}
  labels:
    {{- include "search-services.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.variables.configmap | nindent 2}}
{{- end }}