import { DateTimeFilter } from "../../util/DateTimeFilter";
import { StringFilter } from "../../util/StringFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { BooleanFilter } from "../../util/BooleanFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { ProfileWhereUniqueInput } from "../profile/ProfileWhereUniqueInput";
import { JsonFilter } from "../../util/JsonFilter";
import { TeamListRelationFilter } from "../team/TeamListRelationFilter";
import { WorkspaceListRelationFilter } from "../workspace/WorkspaceListRelationFilter";

export type UserWhereInput = {
  createdAt?: DateTimeFilter;
  email?: StringFilter;
  firstName?: StringNullableFilter;
  id?: StringFilter;
  isActive?: BooleanNullableFilter;
  isAdmin?: BooleanFilter;
  isViewer?: BooleanNullableFilter;
  language?: StringNullableFilter;
  lastActiveAt?: DateTimeNullableFilter;
  lastName?: StringNullableFilter;
  password?: StringFilter;
  profile?: ProfileWhereUniqueInput;
  profileId?: StringFilter;
  roles?: JsonFilter;
  teams?: TeamListRelationFilter;
  updatedAt?: DateTimeFilter;
  username?: StringFilter;
  workspaces?: WorkspaceListRelationFilter;
};
